services:
  - type: web
    name: fesee-mock-api
    env: node
    region: singapore
    plan: free
    buildCommand: cd mock-api && npm install
    startCommand: cd mock-api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
